/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    val caso1 = new Programacion()
    println(caso1.maxLin(List(1, 2, 3, 4, 5, 70,22,110,6, 7, 8, 9, 10)))//Debe imprimir 110
    println(caso1.maxIt(List(3,1,6,2,9)))//Debe imprimir 9
    println(caso1.maxIt(List(3,1,6,66,2,9,20)))//Debe imprimir 66
    println(caso1.maxIt(List(3,7,2,5)))//Debe imprimir 7

    //pruebas para hanoi
    val caso2 = new TorresHanoi()
    println(caso2.movsTorresHanoi(4))//Debe imprimir 15
    println(caso2.movsTorresHanoi(3))//Debe imprimir 7  
    println(caso2.torresHanoi(3,1,2,3))//Debe imprimir List((1,3), (1,2), (3,2), (1,3), (2,1), (2,3), (1,3))
    println(caso2.torresHanoi(4,1,2,3))//Debe imprimir List((1,2), (1,3), (2,3), (1,2), (3,1), (3,2), (1,2), (1,3), (2,3), (2,1), (3,1), (2,3), (1,2), (1,3), (2,3))

  }
}
